"""initalized product catalog tables

Revision ID: b628de470cd2
Revises: 
Create Date: 2026-06-14 03:10:22.827727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b628de470cd2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_families',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_custom_pricing', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_catalog_outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('publish_attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_outbox_unpublished', 'product_catalog_outbox', ['created_at'], unique=False, postgresql_where=sa.text('published = false'))
    op.create_table('plan_entitlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('feature_key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['plan_families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'plan_version', 'feature_key', name='uq_plan_entitlements_feature')
    )
    op.create_index('idx_plan_entitlements_plan', 'plan_entitlements', ['family_id', 'plan_version'], unique=False)
    op.create_index('idx_plan_entitlements_value', 'plan_entitlements', ['value'], unique=False, postgresql_using='gin')
    op.create_table('plan_pricing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['plan_families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'plan_version', 'currency', name='uq_plan_pricing_plan_version_currency')
    )
    op.create_index('idx_plan_pricing_plan', 'plan_pricing', ['family_id', 'plan_version'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['plan_families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'version', name='uq_plans_family_version')
    )
    op.create_index('idx_plans_active', 'plans', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_plans_active', table_name='plans', postgresql_where=sa.text('is_active = true'))
    op.drop_table('plans')
    op.drop_index('idx_plan_pricing_plan', table_name='plan_pricing')
    op.drop_table('plan_pricing')
    op.drop_index('idx_plan_entitlements_value', table_name='plan_entitlements', postgresql_using='gin')
    op.drop_index('idx_plan_entitlements_plan', table_name='plan_entitlements')
    op.drop_table('plan_entitlements')
    op.drop_index('idx_outbox_unpublished', table_name='product_catalog_outbox', postgresql_where=sa.text('published = false'))
    op.drop_table('product_catalog_outbox')
    op.drop_table('plan_families')
    # ### end Alembic commands ###
